version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./templates:/app/templates
      - ./img:/app/img
    env_file:
      - .env
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1         # <-- Esto muestra prints en consola
      - PYTHONUNBUFFERED=1    # <-- IMPORTANTE: Muestra prints inmediatamente
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

      - USERNAME_SIGENU=${USERNAME_SIGENU}
      - PASSWORD_SIGENU=${PASSWORD_SIGENU}

      - USER_NEXTCLOUD=${USER_NEXTCLOUD}
      - PASS_NEXTCLOUD=${PASS_NEXTCLOUD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sports_network
    
  
  frontend:
    image: node:20-alpine
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - sports_network
    depends_on:
      - backend
    environment:
    - NEXT_PUBLIC_API_URL=http://backend:8000

  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/0-init-db.sh
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-sports_league_owner}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sports_league_password}
      - POSTGRES_DB=${POSTGRES_DB:-sports_league}
    ports:
      - "5432:5432"
    networks:
      - sports_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sports_league_owner} -d ${POSTGRES_DB:-sports_league}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  sports_network:
    driver: bridge 